eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
      prefer-ip-address: true
